# Creating data with pyRANN

## 2) Elastic Strain
First, let's load an FCC Al structure from our POSCAR file, "Al.POSCAR".

In [1]:
import pyrann as rann
import numpy as np

fcc = rann.load('Al.POSCAR')
print(fcc)

Initializing pyrann version 1.0.0.a1
box and atoms are column vectors
System created from Al.POSCAR
box = 
[[2.473329 0.824443 0.      ]
 [0.       2.331877 0.      ]
 [1.427977 1.427977 2.855955]]
natoms = 1
elements = ['Al']
timestep = None
types = [1]
atoms = 
[[0.]
 [0.]
 [0.]]
energy = 0
forces = 
None
stress = 
None


Now we can apply an elastic strain on our system.
We will generate 100 unique structures for each of the following strain modes in Voigt notation:
| $\varepsilon_1$ | $\varepsilon_2$ | $\varepsilon_3$ | $\varepsilon_4$ | $\varepsilon_5$ | $\varepsilon_6$ |
|---|---|---|---|---|---|
| $\varepsilon$ | $\varepsilon$ | $\varepsilon$ | 0 | 0 | 0 |
| $\varepsilon$ | 0 | 0 | 0 | 0 | 0 |
| 0 | $\varepsilon$ | 0 | 0 | 0 | 0 |
| 0 | 0 | $\varepsilon$ | 0 | 0 | 0 |
| 0 | 0 | 0 | $\varepsilon$ | 0 | 0 |
| 0 | 0 | 0 | 0 | $\varepsilon$ | 0 |
| 0 | 0 | 0 | 0 | 0 | $\varepsilon$ |
| 0 | 0 | 0 | $\varepsilon$ | $\varepsilon$ | $\varepsilon$ |
| $\varepsilon$ | $\varepsilon$ | 0 | 0 | 0 | 0 |
| $\varepsilon$ | $-\varepsilon$ | 0 | 0 | 0 | 0 |
| $\varepsilon$ | $\varepsilon$ | $\varepsilon$ | $\varepsilon$ | $\varepsilon$ | $\varepsilon$ |

We will apply a maximum strain of 5%. This means, for each strain mode,
$\varepsilon$ will vary from -5% to +5% strain in equal increments across the 100 unique structures.

In [2]:
strain = fcc.strain(strain_points=100, maximum_strain = 0.05)

"strain" is now an instance of the series class. A series class object contains a list of system class objects.
We can export the strain series instance to a file.

In [3]:
strain.export('strain.dump')

If we wanted individual POSCAR files for each unique structure, we can do the following:

In [4]:
strain.export('strain.POSCAR', directory='POSCARS')

## 3) Create Supercell
For other types of data, we may want more than just a primitive cell. Let's create a supercell.

In [5]:
new_box = fcc.box*np.array([4, 4, 4])
fcc.createsupercell(new_box=new_box)
print(fcc)

box and atoms are column vectors
System created from Al.POSCAR
box = 
[[10.5056556   3.81166298  0.2694119 ]
 [ 0.3680234   9.99030378  0.2694119 ]
 [ 6.2209874   6.28541626 11.97534401]]
natoms = 64
elements = ['Al']
timestep = None
types = [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
atoms = 
[[3.81879711e-03 7.11717724e-02 1.38524748e-01 2.05877723e-01
  9.56734543e-01 1.02408752e+00 1.09144049e+00 1.15879347e+00
  1.90965029e+00 1.97700326e+00 2.04435624e+00 2.11170922e+00
  2.86256604e+00 2.92991901e+00 2.99727199e+00 3.06462496e+00
  2.63023270e+00 2.69758567e+00 2.76493865e+00 2.83229162e+00
  3.58314844e+00 3.65050142e+00 3.71785439e+00 3.78520737e+00
  4.53606419e+00 4.60341716e+00 4.67077014e+00 4.73812311e+00
  5.48897993e+00 5.55633291e+00 5.62368588e+00 5.69103886e+00
  5.25664659e+00 5.32399957e+00 5.39135255e+00 5.45870552e+00
  6.20956234e+00 6.27691532e+00 6.34426829e+00 6.41162127e+0

The createsupercell method modifies the attributes of the system instance passed to it. 
This means you will need to load in a new instance of "Al.POSCAR" if you need the primitive cell again.

## 4) Thermal Perturbations
Now that we have a supercell, let's generate data to mimic thermal perturbations.

We will create 100 "unique" structures with a maximum perturbation of 5% of Al lattice constant ($4.0495 \mathring{A} *0.05=0.202475 \mathring{A}$).
We will also randomly strain the box by 5% and export to a LAMMPS dump file.

In [6]:
thermal = fcc.thermal(temp=0.202475, strain=0.05, nsims=100)
thermal.export('thermal.dump')

## 5) Vacancies
Now let's add a vacancy to our supercell. We do this by randomly deleting one atom.

In [7]:
fcc.vacancy(num_neighbors=1)
print(fcc)

box and atoms are column vectors
System created from Al.POSCAR
box = 
[[10.5056556   3.81166298  0.2694119 ]
 [ 0.3680234   9.99030378  0.2694119 ]
 [ 6.2209874   6.28541626 11.97534401]]
natoms = 63
elements = ['Al']
timestep = None
types = [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
atoms = 
[[3.81879711e-03 1.38524748e-01 2.05877723e-01 9.56734543e-01
  1.02408752e+00 1.09144049e+00 1.15879347e+00 1.90965029e+00
  1.97700326e+00 2.04435624e+00 2.11170922e+00 2.86256604e+00
  2.92991901e+00 2.99727199e+00 3.06462496e+00 2.63023270e+00
  2.69758567e+00 2.76493865e+00 2.83229162e+00 3.58314844e+00
  3.65050142e+00 3.71785439e+00 3.78520737e+00 4.53606419e+00
  4.60341716e+00 4.67077014e+00 4.73812311e+00 5.48897993e+00
  5.55633291e+00 5.62368588e+00 5.69103886e+00 5.25664659e+00
  5.32399957e+00 5.39135255e+00 5.45870552e+00 6.20956234e+00
  6.27691532e+00 6.34426829e+00 6.41162127e+00 7.16247809e+00


Notice that the vacancy method modifies the attributes of the fcc system instance. This means that any operation
done on "fcc" will now be done on an FCC system containing a vacancy. Let's induce thermal perturbations on this 
system.

In [8]:
thermal_vacancy = fcc.thermal(temp=0.202475, strain=0.05, nsims=100)
thermal_vacancy.export('thermal_vacancy.dump')

We can increase the size of the vacancy by increasing the num_neighbors argument.

In [9]:
fcc.vacancy(num_neighbors=3)
print(fcc)

box and atoms are column vectors
System created from Al.POSCAR
box = 
[[10.5056556   3.81166298  0.2694119 ]
 [ 0.3680234   9.99030378  0.2694119 ]
 [ 6.2209874   6.28541626 11.97534401]]
natoms = 60
elements = ['Al']
timestep = None
types = [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
atoms = 
[[3.81879711e-03 1.38524748e-01 2.05877723e-01 9.56734543e-01
  1.02408752e+00 1.09144049e+00 1.15879347e+00 1.90965029e+00
  1.97700326e+00 2.04435624e+00 2.11170922e+00 2.86256604e+00
  2.92991901e+00 2.99727199e+00 3.06462496e+00 2.63023270e+00
  2.69758567e+00 2.76493865e+00 2.83229162e+00 3.58314844e+00
  3.71785439e+00 3.78520737e+00 4.53606419e+00 4.67077014e+00
  4.73812311e+00 5.48897993e+00 5.55633291e+00 5.62368588e+00
  5.69103886e+00 5.25664659e+00 5.32399957e+00 5.39135255e+00
  5.45870552e+00 6.20956234e+00 6.34426829e+00 6.41162127e+00
  7.16247809e+00 7.22983106e+00 7.29718404e+00 7.36453701e+00
  8.11

Notice how "fcc" now only has 60 atoms. This is because we ran the vacancy method on it twice. The first time, "fcc" went from 64 atoms to 63 atoms because we set num_neighbors=1. The second time we ran the vacancy method, we set num_neighbors=3, so "fcc" went from 63 atoms to 60 atoms. 